# This file will hold any hard configurations MailCannon may need. Customizations included.

# When creating a MailCannon::Envelope the default behavior is to auto-post the Job to send it.
auto_post: true
